### ISSUE TITLE
IDictionary interface support

### ISSUE THREAD

**Issue by Airex** [jeffijoe/messageformat.net#31]
6.0.1
public string FormatMessage(string pattern, IReadOnlyDictionary<string, object?> args) does not accept dictionary as IDictionary
This causes public string FormatMessage(string pattern, object args) this method to be executed

This can be fixed by direct cast, but it breaking change

**Comment by jeffijoe** [comment]
What is the declared type of the value you are passing in? I thought any dictionary type would use the readonly dictionary overload.

**Comment by NightOwl888** [comment]
Built in Dictionaries support `IReadOnlyDictionary<TKey,  TValue>`. However, custom dictionary classes don't usually bother implementing `IReadOnlyDictionary<TKey,  TValue>` or `IDictionary` and only implement `IDictionary<TKey, TValue>` because of the additional work involved. Realistically, to support any dictionary, there should be a check for each of these interfaces.

Do note that generic dictionary interface implementations throw a `KeyNotFoudException` for the indexer getter `this[index]` when a key is not in the dictionary, but non-generic implementations simply return `null` if the key doesn't exist.
